from __future__ import annotations

import json
import logging
import os
import subprocess
import sys

from src.db import connect, log_health
from src.health import HEALTHCHECKS, boot_check

log = logging.getLogger("healthcheck_job")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


ISSUE_LABEL = "auto-health-fail"


def _open_or_update_issue(failures: list[dict]) -> None:
    """Open a GitHub issue for unrepaired failures, or comment on existing one.

    Uses `gh` CLI which is available in GitHub Actions and authenticated by
    GITHUB_TOKEN. Silently no-ops if `gh` isn't on PATH (local runs).
    """
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not repo:
        log.info("GITHUB_REPOSITORY not set — skipping issue creation")
        return
    try:
        existing = subprocess.run(
            ["gh", "issue", "list", "--label", ISSUE_LABEL, "--state", "open",
             "--json", "number,title", "--limit", "1"],
            capture_output=True, text=True, check=True,
        )
        items = json.loads(existing.stdout or "[]")
    except FileNotFoundError:
        log.warning("`gh` not on PATH — skipping issue creation")
        return
    except subprocess.CalledProcessError as e:
        log.warning("gh issue list failed: %s", e.stderr)
        items = []

    body = "## Health check failures\n\n"
    for f in failures:
        body += f"- **{f['name']}**: {f['detail']}\n"
        if f.get("repair_action"):
            body += f"  - repair attempted: {f['repair_action']}\n"
    body += f"\n_Generated by `healthcheck_job.py` at {os.environ.get('GITHUB_RUN_ID', 'local')}_"

    if items:
        num = items[0]["number"]
        subprocess.run(
            ["gh", "issue", "comment", str(num), "--body", body],
            check=False,
        )
        log.info("Appended comment to existing issue #%s", num)
    else:
        subprocess.run(
            ["gh", "issue", "create",
             "--title", "Health check: failures detected",
             "--label", ISSUE_LABEL,
             "--body", body],
            check=False,
        )
        log.info("Opened new health-fail issue")


def _close_open_issues_if_clean() -> None:
    """Close any open auto-health-fail issues since the run is clean."""
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not repo:
        return
    try:
        existing = subprocess.run(
            ["gh", "issue", "list", "--label", ISSUE_LABEL, "--state", "open",
             "--json", "number", "--limit", "20"],
            capture_output=True, text=True, check=True,
        )
        items = json.loads(existing.stdout or "[]")
    except (FileNotFoundError, subprocess.CalledProcessError):
        return
    for item in items:
        subprocess.run(
            ["gh", "issue", "close", str(item["number"]),
             "--comment", "Auto-closed: health check now passing."],
            check=False,
        )
        log.info("Closed issue #%s (now clean)", item["number"])


def main() -> int:
    boot_check("healthcheck")
    failures: list[dict] = []
    repaired_count = 0

    with connect() as conn:
        for chk in HEALTHCHECKS:
            try:
                result = chk.fn()
            except Exception as e:
                result_status = "fail"
                result_detail = f"{type(e).__name__}: {e}"
                log_health(conn, "healthcheck", chk.name, result_status, result_detail)
                failures.append({
                    "name": chk.name, "detail": result_detail, "repair_action": None
                })
                continue

            if result.status == "fail" and chk.repair is not None:
                try:
                    action = chk.repair()
                    log.info("Repair attempted for %s: %s", chk.name, action)
                except Exception as e:
                    action = f"REPAIR FAILED: {type(e).__name__}: {e}"
                    log.exception("Repair raised for %s", chk.name)
                # Re-check
                try:
                    result = chk.fn()
                except Exception as e:
                    result.status = "fail"
                    result.detail = f"recheck error: {type(e).__name__}: {e}"
                if result.status == "pass":
                    log_health(conn, "healthcheck", chk.name, "repaired",
                               result.detail, action)
                    repaired_count += 1
                    continue
                log_health(conn, "healthcheck", chk.name, "fail",
                           result.detail, action)
                failures.append({
                    "name": chk.name, "detail": result.detail,
                    "repair_action": action,
                })
            else:
                log_health(conn, "healthcheck", chk.name, result.status, result.detail)
                if result.status == "fail":
                    failures.append({
                        "name": chk.name, "detail": result.detail,
                        "repair_action": None,
                    })

    log.info("Healthcheck complete: repaired=%d, unresolved_failures=%d",
             repaired_count, len(failures))

    if failures:
        _open_or_update_issue(failures)
        return 1

    _close_open_issues_if_clean()
    return 0


if __name__ == "__main__":
    sys.exit(main())
